services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
    - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  bns-api:
    container_name: bns-api
    image: bns/bns:0.0.1-SNAPSHOT
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on: 
      - postgres

  bns-ui:  
    container_name: bns-ui
    image: bns/bns-ui:1.0.0   
    ports:
      -   :80
    networks:
      - spring-demo
    depends_on:
      - bns-api   

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
